### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by Christilut** [Glavin001/castv2-plex#3]
Hey, thanks for this. Casting from plex isn't that easy but this repo really helped.

I tried your demo and it works until something actually starts loading on the chromecast. It just remains stuck on Loading forever. Any ideas what might be causing that?

**Comment by Christilut** [comment]
I was using an invalid id. Plex accepts the input but instead of showing an error, it will load forever... Had to use `ratingKey` apparently.

**Comment by Glavin001** [comment]
Please feel free to submit Pull Requests for any code or documentation changes 😃 .
